apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devluchops/terraform-k8s-python-hello-argocd.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true