apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: prod

images:
- name: python-hello-world
  newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/python-hello-world
  newTag: stable