apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: dev

images:
- name: python-hello-world
  newName: 292967571313.dkr.ecr.us-east-1.amazonaws.com/python-hello-world
  newTag: latest